M48
; DRILL file {KiCad 7.0.10} date Tuesday, May 05, 2026 at 12:34:14 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-05T12:34:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X91.76Y-91.228
X91.76Y-121.342
X172.06Y-91.26
X172.06Y-121.59
M30
